name: Deploy Snake Game to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Update system packages
          sudo apt update -y

          # Install Python and pip properly
          sudo apt install -y python3 python3-pip
          
          # Ensure pip3 is available in PATH
          export PATH=$HOME/.local/bin:$PATH

          # Remove old application if it exists
          sudo rm -rf ~/SnakeGame

          # Clone the repository
          git clone https://github.com/Sagar2366/season2-snake-game ~/SnakeGame
          cd ~/SnakeGame

          # Manually install dependencies (modify if needed)
          python3 -m pip install --user flask gunicorn

          # Stop any previous instance
          pkill -f "gunicorn" || true

          # Run the app with Gunicorn
          nohup gunicorn --bind 0.0.0.0:5000 app:app > snake_game.log 2>&1 &

          echo "Snake Game deployed successfully"
